apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homekube-self-reflection.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homekube-self-reflection.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homekube-self-reflection.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "homekube-self-reflection.fullname" . }}
  namespace: {{ .Release.Namespace }}

