{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homekube-self-reflection.serviceAccountName" . }}
  labels:
{{ include "homekube-self-reflection.labels" . | nindent 4 }}
{{- end -}}
